### ISSUE TITLE
Issue with Lyrics Display

### ISSUE THREAD

**Issue by DomingoMG** [ClementBeal/audio_metadata_reader#10]
Hi @ClementBeal 

I hope this message finds you well. I wanted to reach out regarding the audio metadata plugin for Dart that you've developed. Firstly, I want to express my appreciation for your work on this plugin, as it has been incredibly helpful.

However, I've encountered an issue with the plugin related to the display of lyrics. Specifically, when attempting to access lyrics in Spanish, the text appears as gibberish characters. This suggests a potential problem with character encoding or support for different character sets.

![Captura de pantalla 2024-05-20 200203](https://github.com/ClementBeal/audio_metadata_reader/assets/36201422/9f1eabb3-8f11-47cd-a1cf-521236716529)

I'm reaching out to bring this to your attention in the hopes that we can find a resolution.
Thank you for your attention to this matter, and I look forward to your response.

Best regards, DomingoMG

**Comment by ClementBeal** [comment]
Hi @DomingoMG ,

Thank you for the issue! 

Could you pass me the audio file that generates this output? I just tried to check the lyrics from my library and I can't see any issue with language using utf-8 character like spanish or french.

Regards,

**Comment by DomingoMG** [comment]
Yes, of course, I attach the audio.

[Adele - Easy On Me.zip](https://github.com/ClementBeal/audio_metadata_reader/files/15392230/Adele.-.Easy.On.Me.zip)

Thanks!

**Comment by ClementBeal** [comment]
Thank you! I'll try to fix it before Monday. I'll ping you when it's done.

**Comment by DomingoMG** [comment]
Hello @ClementBeal, I hope you are well.

I was just stopping by to see if you were able to find out anything, thanks

**Comment by ClementBeal** [comment]
Hi

I have been lazy and forgot the issue, sorry. It's done now with the #27 .
Will be published this week
