### ISSUE TITLE
Wrong duration

### ISSUE THREAD

**Issue by Korvexx** [ClementBeal/audio_metadata_reader#12]
I am unsure whether or not I understand the "duration" output of the readMetadata function.

The audio file (opus) has a duration of "0:02:58", but this is what I get:

**File:**
>[Ab jetzt.zip](https://github.com/user-attachments/files/15740046/Ab.jetzt.zip)

**Code:**
>    final track = File("lib/assets/songs/Ab jetzt.opus");
>
>   final metadata = await readMetadata(track, getImage: false);
>
>    print(metadata.duration);
>    print(metadata.duration!.inMicroseconds);
>    print(metadata.duration!.inSeconds);
>    print(metadata.duration!.inMinutes);

**Output:**
[Ab jetzt.zip](https://github.com/user-attachments/files/15740046/Ab.jetzt.zip)

>flutter: 0:05:58.000000
>flutter: 358000000
>flutter: 358
>flutter: 5

**Comment by Korvexx** [comment]
Maybe something with the "_parseVorbicComment" function?

**Comment by ClementBeal** [comment]
Hi!

I dont have a solution yet. When i'm using `exiftool`, it cannot return a duration. I think I have an idea, let's see

**Comment by Minnowo** [comment]
Is there any progress on this? I've got the same issue.

**Comment by ClementBeal** [comment]
It should be fixed now with the PR #28 
I'll deploy a new version during this week

**Comment by ClementBeal** [comment]
Available in the 0.0.10
