### ISSUE TITLE
Request: Fetching album artist

### ISSUE THREAD

**Issue by joec05** [ClementBeal/audio_metadata_reader#13]
Hi @ClementBeal, I am currently creating a music player app in Flutter as a personal side project, and have been searching for alternatives of FFmpeg to extract a song's metadata since it's pretty slow. I've been getting weird errors when compiling my app with the other plugins such as metadata_god, however I encountered this library and it works great! 

I have a request, which is not urgent of course, that it would be great if I could extract the album's artist as well. To my knowledge, this package supports extracting a song's title, artist, album, duration, etc, but not the album's artist. In FFmpeg I can extract it along with the other metadata, and I think it will be great if it can be done with this package as well.

Thanks in advance and have a great day!

**Comment by ClementBeal** [comment]
Hi!

I'm on it!
