### ISSUE TITLE
Throw an exception instead of returning an InvalidTag object in case of errors.

### ISSUE THREAD

**Issue by Hou-dini** [ClementBeal/audio_metadata_reader#14]
I think this is a wonderful library and I'm keen on using it in my program. However, I have a few issues with regards to how exception handling is implemented for readMetadata function.

I was reading the documentation for readMetadata function when I came across the following statement: "If there's no parser or an error, a InvalidTag instance should be returned." As a user of your library, returning an object with no data when there's an error posses a lot of issues for how that error is handled on my end. For one, returning an instance of InvalidTag from your catch block when it's not a subclass of Exception means there's no way for me to catch and handle the error in my catch block in case an error occurs, since catch blocks only work with subclasses of Exception. Secondly, InvalidTag whose purpose I'm assuming is to indicate an error, inherits from AudioMetadata meaning in case of an error, readMetadata function returns an object instead of throwing an exception which the client's code might not be able to differentiate without dynamic type-checking as it appears like a result and not an error.

Due to the aforementioned issues, I think it would be a cleaner and straightforward design for readMetadata to throw an Exception from the catch block instead of return an InvalidTag object, a subclass of AudioMetadata. You could have readMetadata throw a MetadataException for example, which implements Exception so that as a client I can specifically catch and handle that exception type in my catch block. As the current design stands, that's impossible to do. This is the only issue I have. Thanks for your great work.

**Comment by ClementBeal** [comment]
Hi!

You're totally right. The actual implementation is crap. 

I'll do that tomorrow. It should be quite straightforward to replace this bad class with an exception.

Thanks!

**Comment by Hou-dini** [comment]
Hello!
Glad to hear that. Design is an evolutionary process and I'm happy my
suggestion makes the library better.

Cheers.

**Comment by ClementBeal** [comment]
Done :+1:  #16
