### ISSUE TITLE
Flac metadata is not read

### ISSUE THREAD

**Issue by Feichtmeier** [ClementBeal/audio_metadata_reader#2]
Hi again 👋 

Sadly Flac metadata is not read :(

Here is an example flac
https://upload.wikimedia.org/wikipedia/commons/3/3e/PDP-CH_-_Edith_Lorand_orchestra_-_Der_Vogelh%C3%A4ndler_-_Potpourri_-_Part_1_-_Zeller_-_Parlophon-p9205-20592.flac
The metadta is read by vlc successfully

**Comment by ClementBeal** [comment]
Hi @Feichtmeier,

Thanks for reporting the issue. I have published a fix for that! You can checkout the version `0.0.2` of this package.

In short, it was just a mask mistake. Only one char to change.

**Comment by Feichtmeier** [comment]
> Hi @Feichtmeier,
> 
> Thanks for reporting the issue. I have published a fix for that! You can checkout the version `0.0.2` of this package.
> 
> In short, it was just a mask mistake. Only one char to change.

awesome @ClementBeal it works now for flacs :) 👍 So I think we can close this issue

I just noticed that the picture bytes are empty however (for MP3s, the flacs I have dont have picture bytes) 🤔
