### ISSUE TITLE
Remove dependency to Flutter

### ISSUE THREAD

**Issue by julemand101** [ClementBeal/audio_metadata_reader#3]
Package are described as:
> A pure-Dart package for reading and writing metadata for different audio format

But in `pubspec.yaml` there are dependency to Flutter, `flutter_test` and `flutter_lints`. The last dependency are not that serious but I would recommend changing this package to be a normal Dart package entirely and therefore instead use https://pub.dev/packages/lints.

The dependency to Fluttes does make this "pure-Dart package" not usable for pure-Dart projects. I have looked in all source files and I see no reason for the Flutter dependency. :)

**Comment by ClementBeal** [comment]
Hi!

It seems I have messed up with the project generation or whatever. Thank you for reporting this! I'll be more careful for my future projects :)
