### ISSUE TITLE
MetadataParserException (MetadataParserException : error during the parsing of "storage/emulated/0/Music/اسم عربي.mp3" FormatException: Invalid number (at character 1)

### ISSUE THREAD

**Issue by TheAtef** [ClementBeal/audio_metadata_reader#41]
Please add support for Arabic song names!

**Comment by ClementBeal** [comment]
Hi!

Could you give me a sample please? I don't know if the error is the metadata parsing or just the filename

**Comment by TheAtef** [comment]
Sorry, turns out it wasn't caused by the Arabic filename; I tried with another Arabic filename and it worked.

But still, I tried another song (English filename) and got the same exception (shown below), both songs -that caused this exception- were mp3's.

`MetadataParserException (MetadataParserException : error during the parsing of "storage/emulated/0/Music/02 Goodbye Nostalgia.mp3"
FormatException: Invalid number (at character 1)`


I also was experimenting with other songs and found this:

`Exception has occurred.
MetadataParserException (MetadataParserException : error during the parsing of "storage/emulated/0/Music/07 Neutral Milk Hotel - Communist Daughter.mp3"
No available parser for this file. Please raise an issue in Github)`

I uploaded both songs to [Google Drive](https://drive.google.com/drive/folders/1Ny6sPut8liQZ-aS4UHEDFjKismUqC-bs?usp=sharing) so you can reproduce.

**Comment by ClementBeal** [comment]
For the song `Goodbye Nostalgia`, it's a bug yes. I'll publish a bug fix during this week. In short, it was trying to convert the null character `\0` to a number and obviously, it's not possible.

The second song from your drive is working correctly but it's not the same song than your error. Could you upload the one with the error?
