### ISSUE TITLE
OPUS files render incorrect playtime 

### ISSUE THREAD

**Issue by cblanken** [ClementBeal/audio_metadata_reader#45]
OPUS files seem to yield incorrect playtime values.

See this musicpod issue https://github.com/ubuntu-flutter-community/musicpod/issues/1090 for an example.

As requested, I've attached a few OPUS files here that render incorrectly. See [opus_files.zip](https://github.com/user-attachments/files/18127299/opus_files.zip)

**Comment by ClementBeal** [comment]
Hi!

Finally, it's working correctly! Still thanks you for create the issue!
