### ISSUE TITLE
totalDisc field is null

### ISSUE THREAD

**Issue by Feichtmeier** [ClementBeal/audio_metadata_reader#7]
Hi :wave: 

It appears that the totalDisc field is null
![grafik](https://github.com/ClementBeal/audio_metadata_reader/assets/15329494/88ebf0ff-a72e-4b05-b3fd-3b870e646a87)

in this specific case i am very sure that it is not null in the mp3 :)

Thank you and best regards

**Comment by ClementBeal** [comment]
Hi @Feichtmeier ,

I have pushed a new version fixing this bug (normally). Feel free to try it out :)
